import db from './models/index.js'

const masiniNoi = [
    { marca: 'BMW', model: 'Seria 3 318d', anFabricatie: 2017, km: 142000, combustibil: 1, pretEuro: 14500, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-01', imaginePrincipala: '/images/masini/bmw-seria3.jpg', descriere: 'BMW Seria 3 318d, motor 2.0 diesel 150CP, consum redus, navigație, senzori parcare.', scorViteza: 6.5, scorConfort: 8.0, scorConsum: 8.0, scorManevrabilitate: 7.5, scorPret: 7.5, scorDesignInterior: 8, scorDesignExterior: 8, scorSpatiu: 7, scorAcceleratieCuplu: 6.5, scorFrana: 7.5, idDirector: 1 },
    { marca: 'BMW', model: 'Seria 5 520d xDrive', anFabricatie: 2018, km: 118000, combustibil: 1, pretEuro: 22500, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-02', imaginePrincipala: '/images/masini/bmw-seria3.jpg', descriere: 'BMW Seria 5 520d xDrive, tracțiune integrală, 190CP, interior piele, head-up display.', scorViteza: 7.5, scorConfort: 9.0, scorConsum: 7.5, scorManevrabilitate: 7.5, scorPret: 6.5, scorDesignInterior: 9, scorDesignExterior: 9, scorSpatiu: 8, scorAcceleratieCuplu: 7.5, scorFrana: 8.0, idDirector: 1 },
    { marca: 'BMW', model: 'Seria 4 Gran Coupe 420d', anFabricatie: 2019, km: 89000, combustibil: 1, pretEuro: 26000, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-03', imaginePrincipala: '/images/masini/bmw-seria3.jpg', descriere: 'BMW Seria 4 Gran Coupe, design sportiv 4 uși, 190CP diesel, M Sport package.', scorViteza: 8.0, scorConfort: 8.0, scorConsum: 7.0, scorManevrabilitate: 8.5, scorPret: 6.0, scorDesignInterior: 9, scorDesignExterior: 9, scorSpatiu: 6, scorAcceleratieCuplu: 8.0, scorFrana: 8.5, idDirector: 1 },
    { marca: 'Seat', model: 'Leon FR 1.5 TSI', anFabricatie: 2020, km: 67000, combustibil: 0, pretEuro: 16500, status: 'Disponibil', categorieAuto: 2, locParcare: 'D-04', imaginePrincipala: '/images/masini/seat-leon.jpg', descriere: 'Seat Leon FR, 1.5 TSI 150CP, digital cockpit, CarPlay, design sportiv spaniol.', scorViteza: 7.0, scorConfort: 7.0, scorConsum: 7.5, scorManevrabilitate: 8.0, scorPret: 8.0, scorDesignInterior: 7, scorDesignExterior: 8, scorSpatiu: 7, scorAcceleratieCuplu: 7.0, scorFrana: 7.5, idDirector: 1 },
    { marca: 'Seat', model: 'Ibiza Style 1.0 TSI', anFabricatie: 2021, km: 42000, combustibil: 0, pretEuro: 12800, status: 'Disponibil', categorieAuto: 2, locParcare: 'D-05', imaginePrincipala: '/images/masini/seat-leon.jpg', descriere: 'Seat Ibiza 1.0 TSI 110CP, compactă economică, ideală pentru oraș, Apple CarPlay.', scorViteza: 5.5, scorConfort: 6.5, scorConsum: 8.5, scorManevrabilitate: 8.0, scorPret: 9.0, scorDesignInterior: 6, scorDesignExterior: 7, scorSpatiu: 5, scorAcceleratieCuplu: 5.5, scorFrana: 6.5, idDirector: 1 },
    { marca: 'Seat', model: 'Ateca Xcellence 2.0 TDI', anFabricatie: 2019, km: 95000, combustibil: 1, pretEuro: 18900, status: 'Disponibil', categorieAuto: 4, locParcare: 'D-06', imaginePrincipala: '/images/masini/seat-leon.jpg', descriere: 'Seat Ateca SUV, 2.0 TDI 150CP, navigație, cameră marșarier, design modern.', scorViteza: 6.0, scorConfort: 7.5, scorConsum: 7.5, scorManevrabilitate: 7.0, scorPret: 7.5, scorDesignInterior: 7, scorDesignExterior: 7, scorSpatiu: 8, scorAcceleratieCuplu: 6.0, scorFrana: 7.0, idDirector: 1 },
    { marca: 'Opel', model: 'Corsa-e Electric', anFabricatie: 2022, km: 28000, combustibil: 4, pretEuro: 19500, status: 'Disponibil', categorieAuto: 2, locParcare: 'D-07', imaginePrincipala: '/images/masini/opel-corsa.jpg', descriere: 'Opel Corsa-e 100% electric, 136CP, autonomie 337km, încărcare rapidă.', scorViteza: 6.0, scorConfort: 7.0, scorConsum: 10.0, scorManevrabilitate: 7.5, scorPret: 7.0, scorDesignInterior: 7, scorDesignExterior: 7, scorSpatiu: 5, scorAcceleratieCuplu: 7.0, scorFrana: 7.0, idDirector: 1 },
    { marca: 'Opel', model: 'Insignia Grand Sport 2.0 CDTI', anFabricatie: 2018, km: 132000, combustibil: 1, pretEuro: 13200, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-08', imaginePrincipala: '/images/masini/opel-corsa.jpg', descriere: 'Opel Insignia Grand Sport, sedan premium, 170CP diesel, scaune ergonomice AGR.', scorViteza: 7.0, scorConfort: 8.5, scorConsum: 7.0, scorManevrabilitate: 7.0, scorPret: 8.0, scorDesignInterior: 7, scorDesignExterior: 7, scorSpatiu: 8, scorAcceleratieCuplu: 7.0, scorFrana: 7.0, idDirector: 1 },
    { marca: 'Opel', model: 'Insignia Sports Tourer 1.6 CDTI', anFabricatie: 2017, km: 158000, combustibil: 1, pretEuro: 9800, status: 'Disponibil', categorieAuto: 3, locParcare: 'D-09', imaginePrincipala: '/images/masini/opel-corsa.jpg', descriere: 'Opel Insignia break, portbagaj 560L, 136CP diesel, cruise control, senzori parcare.', scorViteza: 5.5, scorConfort: 8.0, scorConsum: 8.0, scorManevrabilitate: 6.5, scorPret: 8.5, scorDesignInterior: 6, scorDesignExterior: 6, scorSpatiu: 10, scorAcceleratieCuplu: 5.5, scorFrana: 6.5, idDirector: 1 },
    { marca: 'Volkswagen', model: 'Arteon Shooting Brake 2.0 TDI', anFabricatie: 2021, km: 52000, combustibil: 1, pretEuro: 31000, status: 'Disponibil', categorieAuto: 3, locParcare: 'D-10', imaginePrincipala: '/images/masini/vw-arteon.jpg', descriere: 'VW Arteon Shooting Brake, design coupe-break spectaculos, 200CP, DCC, Harman Kardon.', scorViteza: 8.0, scorConfort: 9.0, scorConsum: 7.0, scorManevrabilitate: 8.0, scorPret: 5.5, scorDesignInterior: 9, scorDesignExterior: 10, scorSpatiu: 9, scorAcceleratieCuplu: 8.0, scorFrana: 8.0, idDirector: 1 },
    { marca: 'Volkswagen', model: 'Passat CC 2.0 TDI', anFabricatie: 2016, km: 178000, combustibil: 1, pretEuro: 11500, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-11', imaginePrincipala: '/images/masini/vw-arteon.jpg', descriere: 'VW Passat CC, coupe 4 uși, 150CP diesel, interior elegant, far xenon, climatronic.', scorViteza: 6.5, scorConfort: 8.0, scorConsum: 7.5, scorManevrabilitate: 7.0, scorPret: 8.0, scorDesignInterior: 8, scorDesignExterior: 8, scorSpatiu: 7, scorAcceleratieCuplu: 6.5, scorFrana: 7.0, idDirector: 1 },
    { marca: 'Volkswagen', model: 'Passat B8 Variant 2.0 TDI', anFabricatie: 2019, km: 105000, combustibil: 1, pretEuro: 19800, status: 'Disponibil', categorieAuto: 3, locParcare: 'D-12', imaginePrincipala: '/images/masini/vw-arteon.jpg', descriere: 'VW Passat Variant B8, break premium, 150CP, navigație Discover, ACC, Lane Assist.', scorViteza: 6.5, scorConfort: 8.5, scorConsum: 8.0, scorManevrabilitate: 7.0, scorPret: 7.0, scorDesignInterior: 8, scorDesignExterior: 7, scorSpatiu: 10, scorAcceleratieCuplu: 6.5, scorFrana: 7.5, idDirector: 1 },
    { marca: 'Kia', model: 'Ceed Sedan 1.6 CRDi', anFabricatie: 2020, km: 73000, combustibil: 1, pretEuro: 14200, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-13', imaginePrincipala: '/images/masini/kia-sedan.jpg', descriere: 'Kia Ceed sedan, 136CP diesel, garanție 7 ani, ecran 10.25 inch, cameră 360.', scorViteza: 6.0, scorConfort: 7.5, scorConsum: 8.0, scorManevrabilitate: 7.5, scorPret: 8.5, scorDesignInterior: 7, scorDesignExterior: 7, scorSpatiu: 7, scorAcceleratieCuplu: 6.0, scorFrana: 7.0, idDirector: 1 },
    { marca: 'Kia', model: 'Stinger GT-Line 2.2 CRDi', anFabricatie: 2019, km: 82000, combustibil: 1, pretEuro: 24500, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-14', imaginePrincipala: '/images/masini/kia-sedan.jpg', descriere: 'Kia Stinger, gran turismo sportiv, 200CP diesel, 0-100 în 7.7s, Brembo, Nappa leather.', scorViteza: 8.5, scorConfort: 8.0, scorConsum: 6.5, scorManevrabilitate: 8.5, scorPret: 6.5, scorDesignInterior: 8, scorDesignExterior: 9, scorSpatiu: 7, scorAcceleratieCuplu: 8.5, scorFrana: 9.0, idDirector: 1 },
    { marca: 'Kia', model: 'Optima 1.7 CRDi', anFabricatie: 2017, km: 148000, combustibil: 1, pretEuro: 8900, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-24', imaginePrincipala: '/images/masini/kia-sedan.jpg', descriere: 'Kia Optima sedan, 141CP diesel, design Peter Schreyer, spațios, preț accesibil.', scorViteza: 5.5, scorConfort: 7.5, scorConsum: 8.0, scorManevrabilitate: 6.5, scorPret: 9.5, scorDesignInterior: 7, scorDesignExterior: 7, scorSpatiu: 8, scorAcceleratieCuplu: 5.5, scorFrana: 6.5, idDirector: 1 },
    { marca: 'Mercedes-Benz', model: 'CLA 200d Coupe', anFabricatie: 2020, km: 58000, combustibil: 1, pretEuro: 27500, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-15', imaginePrincipala: '/images/masini/mercedes-cla.jpg', descriere: 'Mercedes CLA 200d, coupe 4 uși, 150CP, MBUX, ambient lighting 64 culori.', scorViteza: 6.5, scorConfort: 8.5, scorConsum: 8.0, scorManevrabilitate: 7.5, scorPret: 6.0, scorDesignInterior: 9, scorDesignExterior: 10, scorSpatiu: 6, scorAcceleratieCuplu: 6.5, scorFrana: 7.5, idDirector: 1 },
    { marca: 'Mercedes-Benz', model: 'CLS 350d 4MATIC', anFabricatie: 2018, km: 98000, combustibil: 1, pretEuro: 35000, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-16', imaginePrincipala: '/images/masini/mercedes-cla.jpg', descriere: 'Mercedes CLS, coupe premium, 286CP V6, tracțiune integrală, Burmester, Multibeam LED.', scorViteza: 8.5, scorConfort: 9.5, scorConsum: 6.5, scorManevrabilitate: 7.5, scorPret: 4.5, scorDesignInterior: 10, scorDesignExterior: 10, scorSpatiu: 7, scorAcceleratieCuplu: 8.5, scorFrana: 8.5, idDirector: 1 },
    { marca: 'Suzuki', model: 'Swace Hybrid', anFabricatie: 2022, km: 31000, combustibil: 3, pretEuro: 18500, status: 'Disponibil', categorieAuto: 3, locParcare: 'D-17', imaginePrincipala: '/images/masini/suzuki-break.jpg', descriere: 'Suzuki Swace break hybrid, 1.8L 140CP, consum 3.5L/100km, portbagaj 596L, fiabil.', scorViteza: 5.0, scorConfort: 7.5, scorConsum: 10.0, scorManevrabilitate: 7.0, scorPret: 8.0, scorDesignInterior: 6, scorDesignExterior: 6, scorSpatiu: 9, scorAcceleratieCuplu: 5.0, scorFrana: 6.5, idDirector: 1 },
    { marca: 'Suzuki', model: 'SX4 S-Cross 1.4 Boosterjet', anFabricatie: 2020, km: 65000, combustibil: 0, pretEuro: 15800, status: 'Disponibil', categorieAuto: 4, locParcare: 'D-18', imaginePrincipala: '/images/masini/suzuki-break.jpg', descriere: 'Suzuki SX4 S-Cross, crossover compact, 140CP turbo, 4x4 AllGrip, ideal drumuri grele.', scorViteza: 6.5, scorConfort: 7.0, scorConsum: 7.0, scorManevrabilitate: 7.5, scorPret: 8.0, scorDesignInterior: 6, scorDesignExterior: 6, scorSpatiu: 7, scorAcceleratieCuplu: 6.5, scorFrana: 7.0, idDirector: 1 },
    { marca: 'Honda', model: 'Civic Sedan 1.5 VTEC Turbo', anFabricatie: 2020, km: 55000, combustibil: 0, pretEuro: 19900, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-19', imaginePrincipala: '/images/masini/honda-sedan.jpg', descriere: 'Honda Civic sedan, 182CP turbo, design agresiv, Honda Sensing, consum excelent.', scorViteza: 8.0, scorConfort: 7.5, scorConsum: 7.5, scorManevrabilitate: 8.5, scorPret: 7.0, scorDesignInterior: 7, scorDesignExterior: 8, scorSpatiu: 7, scorAcceleratieCuplu: 8.0, scorFrana: 7.5, idDirector: 1 },
    { marca: 'Honda', model: 'Accord 2.0 i-VTEC', anFabricatie: 2017, km: 125000, combustibil: 0, pretEuro: 13500, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-20', imaginePrincipala: '/images/masini/honda-sedan.jpg', descriere: 'Honda Accord sedan mare, 155CP, fiabilitate legendară, spațios, ideal familie.', scorViteza: 6.0, scorConfort: 8.0, scorConsum: 7.0, scorManevrabilitate: 6.5, scorPret: 8.0, scorDesignInterior: 7, scorDesignExterior: 7, scorSpatiu: 9, scorAcceleratieCuplu: 6.0, scorFrana: 7.0, idDirector: 1 },
    { marca: 'Honda', model: 'Shuttle Hybrid', anFabricatie: 2019, km: 78000, combustibil: 3, pretEuro: 16200, status: 'Disponibil', categorieAuto: 3, locParcare: 'D-21', imaginePrincipala: '/images/masini/honda-sedan.jpg', descriere: 'Honda Shuttle break hybrid, portbagaj 570L, consum 4.2L hybrid, spațiu maxim.', scorViteza: 5.0, scorConfort: 8.0, scorConsum: 9.5, scorManevrabilitate: 6.5, scorPret: 7.5, scorDesignInterior: 6, scorDesignExterior: 6, scorSpatiu: 10, scorAcceleratieCuplu: 5.0, scorFrana: 6.5, idDirector: 1 },
    { marca: 'Infiniti', model: 'Q50 2.0t Sport', anFabricatie: 2018, km: 88000, combustibil: 0, pretEuro: 21000, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-22', imaginePrincipala: '/images/masini/infiniti-sedan.jpg', descriere: 'Infiniti Q50, sedan premium japonez, 211CP turbo, interior Bose, adaptive steering.', scorViteza: 8.0, scorConfort: 8.5, scorConsum: 6.5, scorManevrabilitate: 8.0, scorPret: 6.5, scorDesignInterior: 8, scorDesignExterior: 8, scorSpatiu: 7, scorAcceleratieCuplu: 8.0, scorFrana: 7.5, idDirector: 1 },
    { marca: 'Infiniti', model: 'Q70 3.5 Hybrid', anFabricatie: 2016, km: 135000, combustibil: 3, pretEuro: 17500, status: 'Disponibil', categorieAuto: 1, locParcare: 'D-23', imaginePrincipala: '/images/masini/infiniti-sedan.jpg', descriere: 'Infiniti Q70 hybrid, limuzină japoneză, 364CP combinat, scaune ventilate, suspensie adaptivă.', scorViteza: 8.5, scorConfort: 9.5, scorConsum: 7.0, scorManevrabilitate: 7.0, scorPret: 7.0, scorDesignInterior: 9, scorDesignExterior: 8, scorSpatiu: 8, scorAcceleratieCuplu: 8.5, scorFrana: 8.0, idDirector: 1 },
]

async function insert() {
    console.log('Inserare 24 mașini noi...')
    for (const m of masiniNoi) {
        await db.Masina.create(m)
        console.log(`  ✅ ${m.marca} ${m.model} — €${m.pretEuro}`)
    }
    const total = await db.Masina.count()
    console.log(`\nTotal mașini în DB: ${total}`)
    process.exit(0)
}

insert().catch(e => { console.error('Eroare:', e.message); process.exit(1) })
